variable "dynamodb_table_name_override" {}
variable "environment" {}
variable "project" {}
variable "enable_point_in_time_recovery" {}
variable "dynamodb_max_read_capacity" {}
variable "dynamodb_min_read_capacity" {}
variable "dynamodb_max_write_capacity" {}
variable "dynamodb_min_write_capacity" {}
variable "enable_dynamodb_autoscaling" {}
variable "enable" {}
